version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - OPTLP_ENDPOINT=http://tempo:4318
      - SERVICE_NAME=go-opentelemetry
      - DB_HOST=localhost
      - DB_USER=joeshiett
      - DB_NAME=postgres
      - DB_PASSWORD=123456
      - SSL_MODE=disable

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"